name: Add Issue to Project

on:
  issues:
    types: [ opened ] ############ exclude pull requests and items that already have a Project

  workflow_dispatch:

jobs:
  steve:
    runs-on: ubuntu-latest
    steps:
      - name: get backlog field ID
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ORGANIZATION: josephmyers
        run: |
          echo issue $ISSUE_NUMBER created
          
          gh api graphql -f query='
            query($org: String!) {
              user(login: $org){
                projectNext(number: 1) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION > project_data.json
            
          echo 'PROJECT_ID='$(jq '.data.user.projectNext.id' project_data.json) >> $GITHUB_ENV
          echo 'FIELD_ID='$(jq '.data.user.projectNext.fields.nodes[] | select(.name== "Backlog") | .id' project_data.json) >> $GITHUB_ENV
        
      - name: set fields
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation(
              $project:ID!
              $item:ID!
              $field: ID!
              $field_value: String!)
            {
              addProjectNextItem(input: {projectId: $project, contentId: $item})
              {
                projectNextItem {
                  id
                }
              }
              updateProjectNextItemField(input: {
                projectId: $project
                itemId: $item
                fieldId: $field
                value: $field_value})
              {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f item=$ISSUE_NUMBER -f field=$FIELD_ID -f field_value=Triage
            
