name: Add Issue to Project

on:
  issues:
    types: [ opened ] ############ exclude pull requests and items that already have a Project

  workflow_dispatch:

jobs:
  steve:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@2dcfef1aa3f19127e0b9a90f80b133af4c756dff
        with:
          app_id: ${{ secrets.LFPROJECTBOARDAUTOMATION_APP_ID }}
          private_key: ${{ secrets.LFPROJECTBOARDAUTOMATION_PRIVATE_KEY }}
          
      - name: get backlog field ID
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NUMBER: ${{ github.event.issue.number }}
          ORGANIZATION: josephmyers ###############################
        run: |
          echo issue $NUMBER created
          
          gh api graphql -f query='
            query($org: String!) {
              organization(login: $org){
                projectNext(number: 1) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION > project_data.json
            
          echo 'FIELD='$(jq '.data.organization.projectNext.fields.nodes[] | select(.name== "Backlog") | .id' project_data.json) >> $GITHUB_ENV
        
      - name: set fields
        run: |
          gh api graphql -f query='
            mutation(
              $project:ID!
              $item:ID!
              $field: ID!
              $field_value: String!)
            {
              addProjectNextItem(input: {projectId: $project, contentId: $item})
              {
                projectNextItem {
                  id
                }
              }
              updateProjectNextItemField(input: {
                projectId: $project
                itemId: $item
                fieldId: $field
                value: $field_value})
              {
                projectNextItem {
                  id
                }
              }
            }' -f project=1 -f item=$NUMBER -f field=$FIELD -f field_value=Triage
            
